"""agregar detalle a alarmas y tabla eventos_raw

Revision ID: 56b1590ad3b1
Revises: 
Create Date: 2026-07-12 18:03:02.831202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b1590ad3b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipo_alarma', sa.String(), nullable=False),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('modulo', sa.String(), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarmas_id'), 'alarmas', ['id'], unique=False)
    op.create_index(op.f('ix_alarmas_timestamp'), 'alarmas', ['timestamp'], unique=False)
    op.create_table('configuracion_modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(), nullable=False),
    sa.Column('parametro', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_modulos_id'), 'configuracion_modulos', ['id'], unique=False)
    op.create_table('eventos_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('contenido_raw', sa.String(), nullable=False),
    sa.Column('modulo', sa.String(), nullable=False),
    sa.Column('procesado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_raw_id'), 'eventos_raw', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_raw_ip_origen'), 'eventos_raw', ['ip_origen'], unique=False)
    op.create_index(op.f('ix_eventos_raw_timestamp'), 'eventos_raw', ['timestamp'], unique=False)
    op.create_table('usuarios_web',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_web_id'), 'usuarios_web', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_web_username'), 'usuarios_web', ['username'], unique=True)
    op.create_table('acciones_prevencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarma_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alarma_id'], ['alarmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acciones_prevencion_id'), 'acciones_prevencion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acciones_prevencion_id'), table_name='acciones_prevencion')
    op.drop_table('acciones_prevencion')
    op.drop_index(op.f('ix_usuarios_web_username'), table_name='usuarios_web')
    op.drop_index(op.f('ix_usuarios_web_id'), table_name='usuarios_web')
    op.drop_table('usuarios_web')
    op.drop_index(op.f('ix_eventos_raw_timestamp'), table_name='eventos_raw')
    op.drop_index(op.f('ix_eventos_raw_ip_origen'), table_name='eventos_raw')
    op.drop_index(op.f('ix_eventos_raw_id'), table_name='eventos_raw')
    op.drop_table('eventos_raw')
    op.drop_index(op.f('ix_configuracion_modulos_id'), table_name='configuracion_modulos')
    op.drop_table('configuracion_modulos')
    op.drop_index(op.f('ix_alarmas_timestamp'), table_name='alarmas')
    op.drop_index(op.f('ix_alarmas_id'), table_name='alarmas')
    op.drop_table('alarmas')
    # ### end Alembic commands ###
